// src/fleet-ui/components/ThemeSwitch.vue
<script setup>
/* 5-way theme switch (§4). Lives in the Side-Menu footer. In rail mode the
   parent CSS stacks the buttons; pass :cycle to render one cycling button. */
import { ref } from "vue";
import { THEMES, getTheme, setTheme, cycleTheme } from "../theme.js";
import { THEME_ICON } from "../icons/index.js";
import FleetIcon from "./FleetIcon.vue";

defineProps({ cycle: { type: Boolean, default: false } });
const current = ref(getTheme());

function pick(t) { current.value = setTheme(t); }
function next() { current.value = cycleTheme(); }
</script>

<template>
  <button
    v-if="cycle"
    class="fleet-nav-item"
    :title="`Theme: ${current}`"
    @click="next"
  >
    <span class="icon"><FleetIcon :name="THEME_ICON[current]" /></span>
    <span class="label">{{ current }}</span>
  </button>

  <div v-else class="fleet-theme-switch" role="group" aria-label="Theme">
    <button
      v-for="t in THEMES"
      :key="t"
      :aria-pressed="String(t === current)"
      :title="t"
      @click="pick(t)"
    >
      <FleetIcon :name="THEME_ICON[t]" :size="14" />
    </button>
  </div>
</template>

// src/fleet/ThemeSwitch.jsx
import { THEMES, DENSITIES } from './useFleetTheme.js'
import { Icon, THEME_ICON } from './icons.jsx'

export default function ThemeSwitch({ theme, setTheme, density, setDensity, rail }) {
  if (rail) {
    const next = () => {
      const i = THEMES.indexOf(theme)
      setTheme(THEMES[(i + 1) % THEMES.length])
    }
    return (
      <button className="fleet-nav-item" title={`Theme: ${theme}`} onClick={next}>
        <span className="icon"><Icon name={THEME_ICON[theme]} /></span>
        <span className="label">{theme}</span>
      </button>
    )
  }
  return (
    <>
      <div className="fleet-theme-switch" role="group" aria-label="Theme">
        {THEMES.map(t => (
          <button
            key={t}
            aria-pressed={t === theme}
            title={t}
            onClick={() => setTheme(t)}
          >
            <Icon name={THEME_ICON[t]} size={14} />
          </button>
        ))}
      </div>
      <label className="fleet-density-toggle">
        <input
          type="checkbox"
          checked={density === 'compact'}
          onChange={e => setDensity(e.target.checked ? 'compact' : 'comfortable')}
        />
        Compact
      </label>
    </>
  )
}
